<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personnel extends \App\Entity\Personnel implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'archived' => [parent::class, 'archived', null],
        "\0".parent::class."\0".'datecon' => [parent::class, 'datecon', null],
        "\0".parent::class."\0".'daten' => [parent::class, 'daten', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'evaluation' => [parent::class, 'evaluation', null],
        "\0".parent::class."\0".'fonction' => [parent::class, 'fonction', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'jourc' => [parent::class, 'jourc', null],
        "\0".parent::class."\0".'lieun' => [parent::class, 'lieun', null],
        "\0".parent::class."\0".'motpasse' => [parent::class, 'motpasse', null],
        "\0".parent::class."\0".'navire' => [parent::class, 'navire', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'sexe' => [parent::class, 'sexe', null],
        "\0".parent::class."\0".'tel' => [parent::class, 'tel', null],
        "\0".parent::class."\0".'typep' => [parent::class, 'typep', null],
        'archived' => [parent::class, 'archived', null],
        'datecon' => [parent::class, 'datecon', null],
        'daten' => [parent::class, 'daten', null],
        'email' => [parent::class, 'email', null],
        'evaluation' => [parent::class, 'evaluation', null],
        'fonction' => [parent::class, 'fonction', null],
        'id' => [parent::class, 'id', null],
        'jourc' => [parent::class, 'jourc', null],
        'lieun' => [parent::class, 'lieun', null],
        'motpasse' => [parent::class, 'motpasse', null],
        'navire' => [parent::class, 'navire', null],
        'nom' => [parent::class, 'nom', null],
        'prenom' => [parent::class, 'prenom', null],
        'sexe' => [parent::class, 'sexe', null],
        'tel' => [parent::class, 'tel', null],
        'typep' => [parent::class, 'typep', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
