<?php

namespace ContainerGwJIkaJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TAOKbsKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tAOKbsK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tAOKbsK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doc' => ['services', 'doctrine', 'getDoctrineService', true],
            'rep' => ['privates', 'App\\Repository\\PersonnelRepository', 'getPersonnelRepositoryService', true],
        ], [
            'doc' => '?',
            'rep' => 'App\\Repository\\PersonnelRepository',
        ]);
    }
}
