<?php

namespace ContainerGwJIkaJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandantControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CommandantController' shared autowired service.
     *
     * @return \App\Controller\CommandantController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CommandantController.php';

        $container->services['App\\Controller\\CommandantController'] = $instance = new \App\Controller\CommandantController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('App\\Controller\\CommandantController', $container));

        return $instance;
    }
}
