<?php

namespace ContainerGxZbENt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FUlWYSmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FUlWYSm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FUlWYSm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'repository' => ['privates', 'App\\Repository\\MouvementRepository', 'getMouvementRepositoryService', true],
        ], [
            'doctrine' => '?',
            'repository' => 'App\\Repository\\MouvementRepository',
        ]);
    }
}
